from .constants import (
    CONNECT_WAIT_S,
    DEFAULT_TIMEOUT_S,
    DEVICE_KEY_PREFIX,
    READ_ONLY_OPS,
    RECONNECT_GRACE_S,
    _connections,
    _last_seen,
    _meta,
    _pending,
    connection_info,
    is_available,
    is_connected,
)
from .rpc import (
    _authenticate,
    _call_once,
    _key_hash,
    _require_pairing,
    _wait_connected,
    call,
)
from ..audit import audit_log
from .routes import (
    PairReq,
    companion_socket,
    list_devices,
    pair_device,
    revoke_device,
    router,
)

__all__ = [
    "DEVICE_KEY_PREFIX",
    "DEFAULT_TIMEOUT_S",
    "RECONNECT_GRACE_S",
    "CONNECT_WAIT_S",
    "READ_ONLY_OPS",
    "_connections",
    "_pending",
    "_meta",
    "_last_seen",
    "connection_info",
    "is_available",
    "is_connected",
    "_wait_connected",
    "_call_once",
    "_key_hash",
    "_require_pairing",
    "_authenticate",
    "call",
    "PairReq",
    "companion_socket",
    "list_devices",
    "pair_device",
    "revoke_device",
    "router",
    "audit_log",
]
