import re
from .dom_theme import render_doc_page, render_slides_page


def _markdown_to_html_dom(content: str, title: str = "", is_slides: bool = False) -> str:
    def esc(s: str) -> str:
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    def inline_format(s: str) -> str:
        s = esc(s)
        s = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', s)
        s = re.sub(r'__(.+?)__', r'<strong>\1</strong>', s)
        s = re.sub(r'\*(.+?)\*', r'<em>\1</em>', s)
        s = re.sub(r'_(.+?)_', r'<em>\1</em>', s)
        s = re.sub(r'`([^`]+)`', r'<code class="inline-code">\1</code>', s)
        return s

    clean_title = title or "Document"
    lines = content.strip().splitlines()

    if is_slides:
        slides = []
        cur_slide = {"title": "", "lines": []}
        for l in lines:
            trimmed = l.strip()
            if trimmed.startswith("---") or (trimmed.startswith("# ") and (cur_slide["title"] or cur_slide["lines"])):
                if cur_slide["title"] or cur_slide["lines"]:
                    slides.append(cur_slide)
                cur_slide = {"title": trimmed[2:].strip() if trimmed.startswith("# ") else "", "lines": []}
            elif trimmed.startswith("# "):
                cur_slide["title"] = trimmed[2:].strip()
            else:
                cur_slide["lines"].append(l)
        if cur_slide["title"] or cur_slide["lines"]:
            slides.append(cur_slide)
        if not slides:
            slides = [{"title": clean_title, "lines": [content]}]

        slides_html = []
        for idx, s in enumerate(slides, 1):
            s_title = inline_format(s["title"] or f"Slide {idx}")
            body_parts = []
            in_ul = False
            for line in s["lines"]:
                t = line.strip()
                if not t:
                    if in_ul:
                        body_parts.append("</ul>")
                        in_ul = False
                    continue
                if t.startswith("- ") or t.startswith("* "):
                    if not in_ul:
                        body_parts.append('<ul class="slide-list">')
                        in_ul = True
                    body_parts.append(f"<li>{inline_format(t[2:])}</li>")
                elif t.startswith("## ") or t.startswith("### "):
                    if in_ul:
                        body_parts.append("</ul>")
                        in_ul = False
                    sub = t.lstrip("#").strip()
                    body_parts.append(f'<h3 class="slide-subtitle">{inline_format(sub)}</h3>')
                else:
                    if in_ul:
                        body_parts.append("</ul>")
                        in_ul = False
                    body_parts.append(f'<p class="slide-text">{inline_format(t)}</p>')
            if in_ul:
                body_parts.append("</ul>")

            slides_html.append(f"""
            <section class="slide">
              <div class="slide-header">
                <h2 class="slide-title">{s_title}</h2>
                <span class="slide-num">{idx:02d} / {len(slides):02d}</span>
              </div>
              <div class="slide-body">
                {''.join(body_parts)}
              </div>
              <div class="slide-footer">
                <span>{esc(clean_title)}</span>
                <span>Generated by Autonomous Agent</span>
              </div>
            </section>
            """)

        return render_slides_page(esc(clean_title), slides_html)

    # Standard Document mode
    body_elements = []
    in_code_block = False
    code_lang = ""
    code_buf = []
    in_ul = False
    in_ol = False
    table_buf = []

    def flush_table():
        nonlocal table_buf
        if not table_buf:
            return
        rows = []
        for tr in table_buf:
            cells = [c.strip() for c in tr.split("|")]
            if tr.startswith("|") and cells and cells[0] == "":
                cells.pop(0)
            if tr.endswith("|") and cells and cells[-1] == "":
                cells.pop()
            if cells:
                rows.append(cells)
        table_buf = []
        if not rows:
            return

        has_header = False
        if len(rows) >= 2 and all(re.match(r"^[\s\-:]+$", c) for c in rows[1]):
            header_row = rows[0]
            data_rows = rows[2:]
            has_header = True
        else:
            header_row = []
            data_rows = rows

        tbl_html = ['<table class="doc-table">']
        if has_header:
            tbl_html.append("<thead><tr>")
            for h in header_row:
                tbl_html.append(f"<th>{inline_format(h)}</th>")
            tbl_html.append("</tr></thead>")
        if data_rows:
            tbl_html.append("<tbody>")
            for r in data_rows:
                tbl_html.append("<tr>")
                for c in r:
                    tbl_html.append(f"<td>{inline_format(c)}</td>")
                tbl_html.append("</tr>")
            tbl_html.append("</tbody>")
        tbl_html.append("</table>")
        body_elements.append("".join(tbl_html))

    for line in lines:
        trimmed = line.strip()

        if trimmed.startswith("```"):
            flush_table()
            if in_code_block:
                escaped_code = esc("\n".join(code_buf))
                body_elements.append(f'<pre class="code-block"><code>{escaped_code}</code></pre>')
                code_buf = []
                in_code_block = False
            else:
                in_code_block = True
                code_lang = trimmed[3:].strip()
            continue

        if in_code_block:
            code_buf.append(line)
            continue

        if trimmed.startswith("|") and trimmed.endswith("|"):
            if in_ul: body_elements.append("</ul>"); in_ul = False
            if in_ol: body_elements.append("</ol>"); in_ol = False
            table_buf.append(trimmed)
            continue
        elif table_buf:
            flush_table()

        if not trimmed:
            if in_ul: body_elements.append("</ul>"); in_ul = False
            if in_ol: body_elements.append("</ol>"); in_ol = False
            continue

        if trimmed.startswith("# "):
            if in_ul: body_elements.append("</ul>"); in_ul = False
            if in_ol: body_elements.append("</ol>"); in_ol = False
            htext = inline_format(trimmed[2:].strip())
            body_elements.append(f'<h1 class="doc-h1">{htext}</h1>')
        elif trimmed.startswith("## "):
            if in_ul: body_elements.append("</ul>"); in_ul = False
            if in_ol: body_elements.append("</ol>"); in_ol = False
            htext = inline_format(trimmed[3:].strip())
            body_elements.append(f'<h2 class="doc-h2">{htext}</h2>')
        elif trimmed.startswith("### "):
            if in_ul: body_elements.append("</ul>"); in_ul = False
            if in_ol: body_elements.append("</ol>"); in_ol = False
            htext = inline_format(trimmed[4:].strip())
            body_elements.append(f'<h3 class="doc-h3">{htext}</h3>')
        elif trimmed.startswith("---") or trimmed.startswith("***"):
            if in_ul: body_elements.append("</ul>"); in_ul = False
            if in_ol: body_elements.append("</ol>"); in_ol = False
            body_elements.append('<hr class="doc-hr"/>')
        elif trimmed.startswith("> "):
            if in_ul: body_elements.append("</ul>"); in_ul = False
            if in_ol: body_elements.append("</ol>"); in_ol = False
            qtext = inline_format(trimmed[2:].strip())
            body_elements.append(f'<blockquote class="doc-quote">{qtext}</blockquote>')
        elif trimmed.startswith("- ") or trimmed.startswith("* "):
            if in_ol: body_elements.append("</ol>"); in_ol = False
            if not in_ul:
                body_elements.append('<ul class="doc-list">')
                in_ul = True
            body_elements.append(f'<li>{inline_format(trimmed[2:].strip())}</li>')
        elif re.match(r'^\d+\.\s+', trimmed):
            if in_ul: body_elements.append("</ul>"); in_ul = False
            if not in_ol:
                body_elements.append('<ol class="doc-ordered">')
                in_ol = True
            m = re.match(r'^\d+\.\s+(.*)', trimmed)
            body_elements.append(f'<li>{inline_format(m.group(1).strip() if m else trimmed)}</li>')
        else:
            if in_ul: body_elements.append("</ul>"); in_ul = False
            if in_ol: body_elements.append("</ol>"); in_ol = False
            ptext = inline_format(trimmed)
            body_elements.append(f'<p class="doc-p">{ptext}</p>')

    if in_code_block and code_buf:
        escaped_code = esc("\n".join(code_buf))
        body_elements.append(f'<pre class="code-block"><code>{escaped_code}</code></pre>')
    if table_buf:
        flush_table()
    if in_ul:
        body_elements.append("</ul>")
    if in_ol:
        body_elements.append("</ol>")

    return render_doc_page(esc(clean_title), body_elements)
