"""routes/mcp_manager.py - MCP connector catalog: list known connectors, authorize one via
OAuth device flow, disconnect one. Tokens are stored in the OS keychain (core/credentials.py)
and never written to config/app.json - only transport/command/args + a "credential_ref"
marker are persisted there. See core/mcp_catalog.py for the connector list.
"""

# core modules the submodules call through; tests patch functions on these
from core import auth_db, credentials, mcp_catalog, mcp_oauth  # noqa: F401
from core import mcp as mcp_core  # noqa: F401

from .base import (
    MANAGE_PERM,
    _manage,
    _use,
    router,
    _server_status,
)
from .models import (
    McpServerReq,
    McpImportReq,
    UserPackagesReq,
    OAuthStartReq,
)
from .validation import (
    _NAME_RX,
    _ENV_KEY_RX,
    _PKG_RX,
    DEFAULT_ALLOWED_COMMANDS,
    _SCRIPT_COMMANDS,
    _USER_COMMANDS,
    _USER_ENV_DENY_PREFIXES,
    _USER_ENV_DENY,
    _allowed_commands,
    _user_packages,
    _SPEC_RX,
    _package_base,
    _validate_user_stdio,
    _validate_script_command,
    _public_url_error,
    _is_internal_host,
    _validate,
    _HEADER_RX,
    _SECRET_HEADERS,
    _validate_auth,
)
from .store import (
    _server_cfg,
    _persist_server_entry,
    _remove_server_entry,
    _can_manage_global,
    _owner_for,
    _restricted,
    _servers_for,
    _custom_cfg,
    _write_server,
    _public_cfg,
    _save_server,
    _bg_tasks,
    _connect_in_background,
    _check_new,
)
from .catalog_endpoints import (
    catalog,
    registry_search,
    authorize_start,
    authorize_poll,
    disable,
)
from .server_endpoints import (
    list_servers,
    add_server,
    update_server,
    delete_server,
    reconnect_server,
    import_servers,
    set_user_packages,
)
from .oauth_endpoints import (
    _redirect_base,
    _loopback_flow,
    oauth_start,
    oauth_status,
    oauth_disconnect,
    _DONE_PAGE,
    oauth_callback,
)

__all__ = [
    "MANAGE_PERM",
    "_manage",
    "_use",
    "router",
    "_server_status",
    "McpServerReq",
    "McpImportReq",
    "UserPackagesReq",
    "OAuthStartReq",
    "_NAME_RX",
    "_ENV_KEY_RX",
    "_PKG_RX",
    "DEFAULT_ALLOWED_COMMANDS",
    "_SCRIPT_COMMANDS",
    "_USER_COMMANDS",
    "_USER_ENV_DENY_PREFIXES",
    "_USER_ENV_DENY",
    "_allowed_commands",
    "_user_packages",
    "_SPEC_RX",
    "_package_base",
    "_validate_user_stdio",
    "_validate_script_command",
    "_public_url_error",
    "_is_internal_host",
    "_validate",
    "_HEADER_RX",
    "_SECRET_HEADERS",
    "_validate_auth",
    "_server_cfg",
    "_persist_server_entry",
    "_remove_server_entry",
    "_can_manage_global",
    "_owner_for",
    "_restricted",
    "_servers_for",
    "_custom_cfg",
    "_write_server",
    "_public_cfg",
    "_save_server",
    "_bg_tasks",
    "_connect_in_background",
    "_check_new",
    "catalog",
    "registry_search",
    "authorize_start",
    "authorize_poll",
    "disable",
    "list_servers",
    "add_server",
    "update_server",
    "delete_server",
    "reconnect_server",
    "import_servers",
    "set_user_packages",
    "_redirect_base",
    "_loopback_flow",
    "oauth_start",
    "oauth_status",
    "oauth_disconnect",
    "_DONE_PAGE",
    "oauth_callback",
]
